services:
 mydb:
  image: mysql
  ports:
   - 3306
  environment:
    MYSQL_ROOT_PASSWORD: Pass@123
    MYSQL_DATABASE: mydatabase
  networks:
    - backend
  volumes:
    - mydata:/var/lib/mysql
 myapp:
  image: php:8.2-fpm
  ports:
    - 9000
  networks:
    - frontend
    - backend
  volumes:
    - mydir:/var/www/html
 myweb:
  image: nginx
  ports:
    - 80:80
  networks:
    - frontend
  depends_on:
    - mydb
  volumes:
    - mydir:/usr/share/nginx/html
networks:
  frontend:
  backend:
volumes:
 mydata: